baseURL = "https://bmunyoki.github.io/Ferntech/"
theme = "dot"
publishDir = "docs"


[params]
primaryColor = "#02007e"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "Ferntech Docs"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "Dot"
  copyright = "© Ferntech 2018."

    # navigation
    [Languages.en.menu]
    
      [[Languages.en.menu.main]]
        weight = 1
        name = "API Docs"
        url = "/api-docs"

      [[Languages.en.menu.main]]
        weight = 2
        name = "Controller"
        url = "/controller"

      [[Languages.en.menu.main]]
        weight = 3
        name = "Faq"
        url = "/faq"
        
      [[Languages.en.menu.main]]

          [[Languages.en.menu.main]]
          parent = "tutorials"
          name = "Installation"
          URL = "/installation"
          weight = 7

          [[Languages.en.menu.main]]
          parent = "tutorials"
          name = "Elements"
          URL = "/elements"
          weight = 6

      [[Languages.en.menu.main]]
        weight = 5
        name = "contact"
        url = "https://infinitefingers.us18.list-manage.com/subscribe?u=6d033c7a74b56324c55a1c895&id=161d71d50c"




    # banner
    [Languages.en.params.banner]
      title = "Community & Knowledge base"
      description = "Find advice and answers from our support team fast or get in touch"
      image = "images/if_home.png"
      placeholder = "Have a question? Just ask here or enter terms"

    # Topics
    [Languages.en.params.topics]
      title = "Browse by subject"
    
    # call to action
    [Languages.en.params.cta]
      enable = true
      title = "Get in Touch"
      description = "What to integrate with us? Didn't find an answer to your question? Having challenges integrating with our API? Contact us"
      btnText = "contact us"
      btnURL = "https://infinitefingers.us18.list-manage.com/subscribe?u=6d033c7a74b56324c55a1c895&id=161d71d50c"

    # contact
    [Languages.en.params.contact]
      title = "Got Any Questions"
      content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    # footer social icon
    [[Languages.en.socialIcon]]
      icon = "ti-twitter-alt"
      URL = "/#"
      
    [[Languages.en.socialIcon]]
      icon = "ti-github"
      URL = "/#"





 